/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiPriorityRouteImport } from './routes/ai-priority'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CoaRouteImport } from './routes/coa'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LiveOperationsRouteImport } from './routes/live-operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PlatformStatusRouteImport } from './routes/platform-status'
import { Route as SignalStatusRouteImport } from './routes/signal-status'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SmmsRouteImport } from './routes/smms'
import { Route as StationMapRouteImport } from './routes/station-map'
import { Route as StationMasterRouteImport } from './routes/station-master'
import { Route as TdmsRouteImport } from './routes/tdms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TmsRouteImport } from './routes/tms'
import { Route as TrackOccupancyRouteImport } from './routes/track-occupancy'
import { Route as TractionStatusRouteImport } from './routes/traction-status'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as WorkstationLocationRouteImport } from './routes/workstation-location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPriorityRoute = AiPriorityRouteImport.update({
  id: '/ai-priority',
  path: '/ai-priority',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaRoute = CoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveOperationsRoute = LiveOperationsRouteImport.update({
  id: '/live-operations',
  path: '/live-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformStatusRoute = PlatformStatusRouteImport.update({
  id: '/platform-status',
  path: '/platform-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalStatusRoute = SignalStatusRouteImport.update({
  id: '/signal-status',
  path: '/signal-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SmmsRoute = SmmsRouteImport.update({
  id: '/smms',
  path: '/smms',
  getParentRoute: () => rootRouteImport,
} as any)
const StationMapRoute = StationMapRouteImport.update({
  id: '/station-map',
  path: '/station-map',
  getParentRoute: () => rootRouteImport,
} as any)
const StationMasterRoute = StationMasterRouteImport.update({
  id: '/station-master',
  path: '/station-master',
  getParentRoute: () => rootRouteImport,
} as any)
const TdmsRoute = TdmsRouteImport.update({
  id: '/tdms',
  path: '/tdms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TmsRoute = TmsRouteImport.update({
  id: '/tms',
  path: '/tms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOccupancyRoute = TrackOccupancyRouteImport.update({
  id: '/track-occupancy',
  path: '/track-occupancy',
  getParentRoute: () => rootRouteImport,
} as any)
const TractionStatusRoute = TractionStatusRouteImport.update({
  id: '/traction-status',
  path: '/traction-status',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkstationLocationRoute = WorkstationLocationRouteImport.update({
  id: '/workstation-location',
  path: '/workstation-location',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-priority': typeof AiPriorityRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/coa': typeof CoaRoute
  '/comparison': typeof ComparisonRoute
  '/incidents': typeof IncidentsRoute
  '/live-operations': typeof LiveOperationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/network': typeof NetworkRoute
  '/planner': typeof PlannerRoute
  '/platform-status': typeof PlatformStatusRoute
  '/signal-status': typeof SignalStatusRoute
  '/simulator': typeof SimulatorRoute
  '/smms': typeof SmmsRoute
  '/station-map': typeof StationMapRoute
  '/station-master': typeof StationMasterRoute
  '/tdms': typeof TdmsRoute
  '/timeline': typeof TimelineRoute
  '/tms': typeof TmsRoute
  '/track-occupancy': typeof TrackOccupancyRoute
  '/traction-status': typeof TractionStatusRoute
  '/work-orders': typeof WorkOrdersRoute
  '/workstation-location': typeof WorkstationLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-priority': typeof AiPriorityRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/coa': typeof CoaRoute
  '/comparison': typeof ComparisonRoute
  '/incidents': typeof IncidentsRoute
  '/live-operations': typeof LiveOperationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/network': typeof NetworkRoute
  '/planner': typeof PlannerRoute
  '/platform-status': typeof PlatformStatusRoute
  '/signal-status': typeof SignalStatusRoute
  '/simulator': typeof SimulatorRoute
  '/smms': typeof SmmsRoute
  '/station-map': typeof StationMapRoute
  '/station-master': typeof StationMasterRoute
  '/tdms': typeof TdmsRoute
  '/timeline': typeof TimelineRoute
  '/tms': typeof TmsRoute
  '/track-occupancy': typeof TrackOccupancyRoute
  '/traction-status': typeof TractionStatusRoute
  '/work-orders': typeof WorkOrdersRoute
  '/workstation-location': typeof WorkstationLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-priority': typeof AiPriorityRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/coa': typeof CoaRoute
  '/comparison': typeof ComparisonRoute
  '/incidents': typeof IncidentsRoute
  '/live-operations': typeof LiveOperationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/network': typeof NetworkRoute
  '/planner': typeof PlannerRoute
  '/platform-status': typeof PlatformStatusRoute
  '/signal-status': typeof SignalStatusRoute
  '/simulator': typeof SimulatorRoute
  '/smms': typeof SmmsRoute
  '/station-map': typeof StationMapRoute
  '/station-master': typeof StationMasterRoute
  '/tdms': typeof TdmsRoute
  '/timeline': typeof TimelineRoute
  '/tms': typeof TmsRoute
  '/track-occupancy': typeof TrackOccupancyRoute
  '/traction-status': typeof TractionStatusRoute
  '/work-orders': typeof WorkOrdersRoute
  '/workstation-location': typeof WorkstationLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-priority'
    | '/alerts'
    | '/analytics'
    | '/audit'
    | '/coa'
    | '/comparison'
    | '/incidents'
    | '/live-operations'
    | '/login'
    | '/maintenance'
    | '/network'
    | '/planner'
    | '/platform-status'
    | '/signal-status'
    | '/simulator'
    | '/smms'
    | '/station-map'
    | '/station-master'
    | '/tdms'
    | '/timeline'
    | '/tms'
    | '/track-occupancy'
    | '/traction-status'
    | '/work-orders'
    | '/workstation-location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-priority'
    | '/alerts'
    | '/analytics'
    | '/audit'
    | '/coa'
    | '/comparison'
    | '/incidents'
    | '/live-operations'
    | '/login'
    | '/maintenance'
    | '/network'
    | '/planner'
    | '/platform-status'
    | '/signal-status'
    | '/simulator'
    | '/smms'
    | '/station-map'
    | '/station-master'
    | '/tdms'
    | '/timeline'
    | '/tms'
    | '/track-occupancy'
    | '/traction-status'
    | '/work-orders'
    | '/workstation-location'
  id:
    | '__root__'
    | '/'
    | '/ai-priority'
    | '/alerts'
    | '/analytics'
    | '/audit'
    | '/coa'
    | '/comparison'
    | '/incidents'
    | '/live-operations'
    | '/login'
    | '/maintenance'
    | '/network'
    | '/planner'
    | '/platform-status'
    | '/signal-status'
    | '/simulator'
    | '/smms'
    | '/station-map'
    | '/station-master'
    | '/tdms'
    | '/timeline'
    | '/tms'
    | '/track-occupancy'
    | '/traction-status'
    | '/work-orders'
    | '/workstation-location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPriorityRoute: typeof AiPriorityRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  CoaRoute: typeof CoaRoute
  ComparisonRoute: typeof ComparisonRoute
  IncidentsRoute: typeof IncidentsRoute
  LiveOperationsRoute: typeof LiveOperationsRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NetworkRoute: typeof NetworkRoute
  PlannerRoute: typeof PlannerRoute
  PlatformStatusRoute: typeof PlatformStatusRoute
  SignalStatusRoute: typeof SignalStatusRoute
  SimulatorRoute: typeof SimulatorRoute
  SmmsRoute: typeof SmmsRoute
  StationMapRoute: typeof StationMapRoute
  StationMasterRoute: typeof StationMasterRoute
  TdmsRoute: typeof TdmsRoute
  TimelineRoute: typeof TimelineRoute
  TmsRoute: typeof TmsRoute
  TrackOccupancyRoute: typeof TrackOccupancyRoute
  TractionStatusRoute: typeof TractionStatusRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
  WorkstationLocationRoute: typeof WorkstationLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-priority': {
      id: '/ai-priority'
      path: '/ai-priority'
      fullPath: '/ai-priority'
      preLoaderRoute: typeof AiPriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa': {
      id: '/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof CoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-operations': {
      id: '/live-operations'
      path: '/live-operations'
      fullPath: '/live-operations'
      preLoaderRoute: typeof LiveOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-status': {
      id: '/platform-status'
      path: '/platform-status'
      fullPath: '/platform-status'
      preLoaderRoute: typeof PlatformStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-status': {
      id: '/signal-status'
      path: '/signal-status'
      fullPath: '/signal-status'
      preLoaderRoute: typeof SignalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smms': {
      id: '/smms'
      path: '/smms'
      fullPath: '/smms'
      preLoaderRoute: typeof SmmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station-map': {
      id: '/station-map'
      path: '/station-map'
      fullPath: '/station-map'
      preLoaderRoute: typeof StationMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station-master': {
      id: '/station-master'
      path: '/station-master'
      fullPath: '/station-master'
      preLoaderRoute: typeof StationMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tdms': {
      id: '/tdms'
      path: '/tdms'
      fullPath: '/tdms'
      preLoaderRoute: typeof TdmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tms': {
      id: '/tms'
      path: '/tms'
      fullPath: '/tms'
      preLoaderRoute: typeof TmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-occupancy': {
      id: '/track-occupancy'
      path: '/track-occupancy'
      fullPath: '/track-occupancy'
      preLoaderRoute: typeof TrackOccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traction-status': {
      id: '/traction-status'
      path: '/traction-status'
      fullPath: '/traction-status'
      preLoaderRoute: typeof TractionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workstation-location': {
      id: '/workstation-location'
      path: '/workstation-location'
      fullPath: '/workstation-location'
      preLoaderRoute: typeof WorkstationLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPriorityRoute: AiPriorityRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  CoaRoute: CoaRoute,
  ComparisonRoute: ComparisonRoute,
  IncidentsRoute: IncidentsRoute,
  LiveOperationsRoute: LiveOperationsRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NetworkRoute: NetworkRoute,
  PlannerRoute: PlannerRoute,
  PlatformStatusRoute: PlatformStatusRoute,
  SignalStatusRoute: SignalStatusRoute,
  SimulatorRoute: SimulatorRoute,
  SmmsRoute: SmmsRoute,
  StationMapRoute: StationMapRoute,
  StationMasterRoute: StationMasterRoute,
  TdmsRoute: TdmsRoute,
  TimelineRoute: TimelineRoute,
  TmsRoute: TmsRoute,
  TrackOccupancyRoute: TrackOccupancyRoute,
  TractionStatusRoute: TractionStatusRoute,
  WorkOrdersRoute: WorkOrdersRoute,
  WorkstationLocationRoute: WorkstationLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
